### ISSUE TITLE
I’m up here - shirt idea

### ISSUE THREAD

**Issue by om-design** [engagingspaces/humane-tech-artwork#4]
#“I’m up here” 
It plays on, and exposes a person’s conditioned reflex to look at a phone screen more readily than a human.

<img width="1366" alt="imuphereshirt" src="https://user-images.githubusercontent.com/1240107/40588068-f97974e0-61a5-11e8-911f-c2db55e6a4f0.png">

**Comment by om-design** [comment]
#needshelp

**Comment by aschrijver** [comment]
I am so sorry @om-design ! The artwork contest that relates to this repository was held from the [Humane Technology community forum](https://community.humanetech.com). But due to the lack of interest by other members (than the participants), it has not been continued. I only see your issue now while referering to another submission (which btw looks similar to yours in concept): 

https://community.humanetech.com/t/idea-smartphone-zombies-or-deliberately-using-language-to-change-habits-and-culture/2710

**Comment by om-design** [comment]
Did interest return? Is still meme worthy.

Om Goeckermann

**Comment by aschrijver** [comment]
> Did interest return?

Not really. I just referred to the artwork created by @micheleminno in my post.
But I could add you to the list of contestants for good measure, if you want.. we might pick this up later.
Are you a member of the Humane Technology community forum?

**Comment by om-design** [comment]
Yes

Om Goeckermann

**Comment by aschrijver** [comment]
I have created an entry for you. Thanks for your interest and participation. If we ever continue the contest for real, it will be announced on the community forum.
